{
  'tracks': {
    'href': 'https://api.spotify.com/v1/search?query=bad+guy&type=track&offset=0&limit=1',
    'items': [
      {
        'album': {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH'
              },
              'href': 'https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH',
              'id': '6qqNVTkY8uBg9cP3Jd7DAH',
              'name': 'Billie Eilish',
              'type': 'artist',
              'uri': 'spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH'
            }
          ],
          'available_markets': [
            'AR',
            'AU',
            'AT',
            'BE',
            'BO',
            'BR',
            'BG',
            'CA',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DK',
            'DO',
            'DE',
            'EC',
            'EE',
            'SV',
            'FI',
            'FR',
            'GR',
            'GT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IE',
            'IT',
            'LV',
            'LT',
            'LU',
            'MY',
            'MT',
            'MX',
            'NL',
            'NZ',
            'NI',
            'NO',
            'PA',
            'PY',
            'PE',
            'PH',
            'PL',
            'PT',
            'SG',
            'SK',
            'ES',
            'SE',
            'CH',
            'TW',
            'TR',
            'UY',
            'US',
            'GB',
            'AD',
            'LI',
            'MC',
            'ID',
            'JP',
            'TH',
            'VN',
            'RO',
            'IL',
            'ZA',
            'SA',
            'AE',
            'BH',
            'QA',
            'OM',
            'KW',
            'EG',
            'MA',
            'DZ',
            'TN',
            'LB',
            'JO',
            'PS',
            'IN',
            'BY',
            'KZ',
            'MD',
            'UA',
            'AL',
            'BA',
            'HR',
            'ME',
            'MK',
            'RS',
            'SI',
            'KR',
            'BD',
            'PK',
            'LK',
            'GH',
            'KE',
            'NG',
            'TZ',
            'UG',
            'AG',
            'AM',
            'BS',
            'BB',
            'BZ',
            'BT',
            'BW',
            'BF',
            'CV',
            'CW',
            'DM',
            'FJ',
            'GM',
            'GE',
            'GD',
            'GW',
            'GY',
            'HT',
            'JM',
            'KI',
            'LS',
            'LR',
            'MW',
            'MV',
            'ML',
            'MH',
            'FM',
            'NA',
            'NR',
            'NE',
            'PW',
            'PG',
            'WS',
            'SM',
            'ST',
            'SN',
            'SC',
            'SL',
            'SB',
            'KN',
            'LC',
            'VC',
            'SR',
            'TL',
            'TO',
            'TT',
            'TV',
            'VU',
            'AZ',
            'BN',
            'BI',
            'KH',
            'CM',
            'TD',
            'KM',
            'GQ',
            'SZ',
            'GA',
            'GN',
            'KG',
            'LA',
            'MO',
            'MR',
            'MN',
            'NP',
            'RW',
            'TG',
            'UZ',
            'ZW',
            'BJ',
            'MG',
            'MU',
            'MZ',
            'AO',
            'CI',
            'DJ',
            'ZM',
            'CD',
            'CG',
            'IQ',
            'LY',
            'TJ',
            'VE',
            'ET',
            'XK'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/0S0KGZnfBGSIssfF54WSJh'
          },
          'href': 'https://api.spotify.com/v1/albums/0S0KGZnfBGSIssfF54WSJh',
          'id': '0S0KGZnfBGSIssfF54WSJh',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ab67616d0000b27350a3147b4edd7701a876c6ce',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/ab67616d00001e0250a3147b4edd7701a876c6ce',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/ab67616d0000485150a3147b4edd7701a876c6ce',
              'width': 64
            }
          ],
          'name': 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
          'release_date': '2019-03-29',
          'release_date_precision': 'day',
          'total_tracks': 14,
          'type': 'album',
          'uri': 'spotify:album:0S0KGZnfBGSIssfF54WSJh'
        },
        'artists': [
          {
            'external_urls': {
              'spotify': 'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH'
            },
            'href': 'https://api.spotify.com/v1/artists/6qqNVTkY8uBg9cP3Jd7DAH',
            'id': '6qqNVTkY8uBg9cP3Jd7DAH',
            'name': 'Billie Eilish',
            'type': 'artist',
            'uri': 'spotify:artist:6qqNVTkY8uBg9cP3Jd7DAH'
          }
        ],
        'available_markets': [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK'
        ],
        'disc_number': 1,
        'duration_ms': 194087,
        'explicit': False,
        'external_ids': {
          'isrc': 'USUM71900764'
        },
        'external_urls': {
          'spotify': 'https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m'
        },
        'href': 'https://api.spotify.com/v1/tracks/2Fxmhks0bxGSBdJ92vM42m',
        'id': '2Fxmhks0bxGSBdJ92vM42m',
        'is_local': False,
        'name': 'bad guy',
        'popularity': 82,
        'preview_url': None,
        'track_number': 2,
        'type': 'track',
        'uri': 'spotify:track:2Fxmhks0bxGSBdJ92vM42m'
      }
    ],
    'limit': 1,
    'next': 'https://api.spotify.com/v1/search?query=bad+guy&type=track&offset=1&limit=1',
    'offset': 0,
    'previous': None,
    'total': 832
  }
}

{
  'collaborative': False,
  'description': 'This is a test',
  'external_urls': {
    'spotify': 'https://open.spotify.com/playlist/4z5IFnZx2g67XlOmEfe9on'
  },
  'followers': {
    'href': None,
    'total': 0
  },
  'href': 'https://api.spotify.com/v1/playlists/4z5IFnZx2g67XlOmEfe9on',
  'id': '4z5IFnZx2g67XlOmEfe9on',
  'images': [

  ],
  'name': 'Billboard Playlist',
  'owner': {
    'display_name': 'Julian',
    'external_urls': {
      'spotify': 'https://open.spotify.com/user/1137868650'
    },
    'href': 'https://api.spotify.com/v1/users/1137868650',
    'id': '1137868650',
    'type': 'user',
    'uri': 'spotify:user:1137868650'
  },
  'primary_color': None,
  'public': False,
  'snapshot_id': 'MSw0OGU4NTdkYWUyNWViNGVmNDc3YjBmYzA4YjQ3MmVmM2UxMDE0Zjgw',
  'tracks': {
    'href': 'https://api.spotify.com/v1/playlists/4z5IFnZx2g67XlOmEfe9on/tracks',
    'items': [

    ],
    'limit': 100,
    'next': None,
    'offset': 0,
    'previous': None,
    'total': 0
  },
  'type': 'playlist',
  'uri': 'spotify:playlist:4z5IFnZx2g67XlOmEfe9on'
}

yeartest = "2006-08-22"

print(yeartest.split('-')[0])